// AUTO-GENERATED from docs-archived/FORMATO VERIFICACION HOTELES ENCORE .xlsx (sheet: Encore)
// Do not edit manually; re-run: node scripts/generate-marketing-template-from-encore.mjs

export const MARKETING_ENCORE_MODEL: Record<string, string[]> = {
  "Anuncio luminoso": [
    "Edificio 1 (motor lobe)",
    "Edificio 2 (Frontal avenida)",
    "Edificio 3 (Lateral Posterior)",
    "Luminoso Tótem",
    "Copete de Tótem",
  ],
  "Recepción": [
    "Tapete de bienvenida",
    "Rool up artista que intervino el Hotel",
    "Logotipo en vinil esmeril + propiedad operada por+ no fumar + cámara de vigilancia",
    "Letrero de gerente en turno",
    "Tarifario",
    "Aviso de privacidad",
    "Mats de WR (2) / YA NO APLICA A PARTIR DE ENERO 2024",
    "Mapa de ubicación del hotel",
    "Tent card porta folletos WR",
    "Condiciones de película roja y logotipo front desk",
    "E concierge ( funcionamiento y Contenido actual)",
    "Mueble porta postales (Condiciones)",
    "Mueble porta postales (Postales)",
    "Condiciones de viniles de artista (Elevador)",
    "Elevadores porta poster",
    "Rol up rome service",
    "Carrito bebida bienvenida (Acrílico)",
    "Caja acrílico de recolección de llaves",
    "Face place (genérico)",
    "Señalética ubicación de maquinas (elevador)",
    "Señalética protección civil",
  ],
  "Sala de juntas": [
    "Viniles esmeriles",
    "Acrílico con QR Wifi y atención WhatsApp",
    "Funcionamiento de los puertos de carga",
    "Señalética protección civil",
  ],
  "The Hub": [
    "Pantallas de computadoras de centro de negocios (Wool paper, Screen saber)",
    "Tent card de información (billar)",
    "Tent card de información (futbolito)",
    "Código Qr en mesa",
    "Blondas (existencia / No recicladas)",
    "Menú",
    "Viniles esmeriles (General)",
    "Porta poster (Baños)",
    "Condiciones de pódium",
    "Señalética protección civil",
    "Pizarrón The Hub",
    "Letreros metálicos bebidas",
    "Visualización de platillos",
    "Acrílico en mesa",
  ],
  "Mezanine": [
    "Acrílico con QR Wifi y atención WhatsApp (dentro de salones)",
    "Roll Up de salones de eventos",
    "Roll Up Genérico (Habitaciones)",
    "Estado de vinil de artista",
    "Porta poster en baños",
    "Señalética protección civil",
    "Señalética Salones de evento",
  ],
  "Gimnasio": [
    "Condiciones de viniles de artistas en pasillo",
    "Viniles esmeriles de gimnasio",
    "Roll up rutina de gimnasio",
    "Reglamento de gimnasio",
  ],
  "Alberca": [
    "Viniles esmeriles",
    "Reglamento de alberca",
    "Tapete de entrada alberca",
    "Vinil de artista",
    "Señalética protección civil",
  ],
  "2do y 3er Piso": [
    "Vending Machine (2do piso)",
  ],
  "2do y 3er Piso / Pasillo": [
    "Condiciones viniles de artista en pasillo",
    "Viniles esmeriles en pasillo",
    "Señalética protección civil",
    "Señalética solo personal autorizado",
  ],
  "Habitación estándar sencilla cama king": [
    "Reglamento interior del Hotel (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Ruta de evacuación (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Door hanger",
    "Formato de tintorería y bolsa de tintorería",
    "Control de aire",
    "Mesa de noche (Tarjetón Sabanas)",
    "Pluma",
    "Blog",
    "Face plate",
    "Código Qr directorio de servicio (Señalética en pared)",
    "Instructivo caja fuete",
    "Señalética burro y plancha",
    "Collarín de agua",
    "Vinil esmeril de regadera",
    "Señalética reusó de toallas",
    "Extracto de intervención",
  ],
  "Habitación estándar queen con sofá cama": [
    "Reglamento interior del Hotel (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Ruta de evacuación (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Door hanger",
    "Formato de tintorería y bolsa de tintorería",
    "Control de aire",
    "Mesa de noche (Tarjetón Sabanas)",
    "Pluma",
    "Blog",
    "Face plate",
    "Código Qr directorio de servicio (Señalética en pared)",
    "Instructivo caja fuete",
    "Señalética burro y plancha",
    "Collarín de agua",
    "Vinil esmeril de regadera",
    "Señalética reusó de toallas",
    "Extracto de intervención",
  ],
  "Habitación doble": [
    "Reglamento interior del Hotel (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Ruta de evacuación (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Door hanger",
    "Formato de tintorería y bolsa de tintorería",
    "Control de aire",
    "Mesa de noche (Tarjetón Sabanas)",
    "Pluma",
    "Blog",
    "Face plate",
    "Código Qr directorio de servicio (Señalética en pared)",
    "Instructivo caja fuete",
    "Señalética burro y plancha",
    "Collarín de agua",
    "Vinil esmeril de regadera",
    "Señalética reusó de toallas",
    "Extracto de intervención",
  ],
  "Habitación junior suite": [
    "Reglamento interior del Hotel (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Ruta de evacuación (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Door hanger",
    "Formato de tintorería y bolsa de tintorería",
    "Control de aire",
    "Mesa de noche (Tarjetón WG)",
    "Pluma",
    "Blog",
    "Face plate",
    "Código Qr directorio de servicio (Señalética en pared)",
    "Instructivo caja fuete",
    "Señalética burro y plancha",
    "Collarín de agua",
    "Vinil esmeril de regadera",
    "Señalética reusó de toallas",
    "Letrero de snack son cortesía (suite)",
    "Surtido Snacks en cortesía",
    "Juego de utensilios (4)",
    "Extracto de intervención",
  ],
  "Habitación junior suite (2)": [
    "Reglamento interior del Hotel (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Ruta de evacuación (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Door hanger",
    "Formato de tintorería y bolsa de tintorería",
    "Control de aire",
    "Mesa de noche (Tarjetón WG)",
    "Pluma",
    "Blog",
    "Face plate",
    "Código Qr directorio de servicio (Señalética en pared)",
    "Instructivo caja fuete",
    "Señalética burro y plancha",
    "Collarín de agua",
    "Vinil esmeril de regadera",
    "Señalética reusó de toallas",
    "Letrero de snack son cortesía (suite)",
    "Surtido Snacks en cortesía",
    "Instructructivo cafetera nespresso (Suite)",
    "Información de tina (Suite)",
    "Mural de intervención (Suite)",
    "Extracto de intervención",
  ],
  "Habitación suite relax": [
    "Reglamento interior del Hotel (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Ruta de evacuación (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Door hanger",
    "Formato de tintorería y bolsa de tintorería",
    "Control de aire",
    "Mesa de noche (Tarjetón sabanas)",
    "Pluma",
    "Blog",
    "Face plate",
    "Código Qr directorio de servicio (Señalética en pared)",
    "Instructivo caja fuete",
    "Señalética burro y plancha",
    "Collarín de agua",
    "Vinil esmeril de regadera",
    "Señalética reusó de toallas",
    "Letrero de snack son cortesía (suite)",
    "Surtido de snacks cortesía",
    "Instructructivo cafetera nespresso (Suite)",
    "Información de tina (Suite)",
    "Mural de intervención (Suite)",
    "Juego de utensilios (4)",
  ],
  "Habitación suite relax (2)": [
    "Reglamento interior del Hotel (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Ruta de evacuación (GDL SUR, QUERETARO, SLP, PUE SEPARADOS) (MTY, AGS y GDL AERO son insertos junto)",
    "Door hanger",
    "Formato de tintorería y bolsa de tintorería",
    "Control de aire",
    "Mesa de noche (Tarjetón sabanas)",
    "Pluma",
    "Blog",
    "Face plate",
    "Código Qr directorio de servicio (Señalética en pared)",
    "Instructivo caja fuete",
    "Señalética burro y plancha",
    "Collarín de agua",
    "Vinil esmeril de regadera",
    "Señalética reusó de toallas",
    "Letrero de snack son cortesía (suite)",
    "Surtido de snacks cortesía",
    "Instructructivo cafetera nespresso (Suite)",
    "Información de tina (Suite)",
    "Mural de intervención (Suite)",
    "Juego de utensilios (2)",
  ],
  "Sótano (GDL SUR, QTO, MYT)": [
    "Direccionamiento vial",
    "Elevador de sótano a planta baja porta poster (QRO y MTY)",
    "Mural de sótano (QRO y MTY)",
    "Viniles esmeril (QRO y MTY)",
  ],
  "Autos de mensajería": [
    "Rotulos y medallones",
  ],
  "Música ambiental": [
    "Música ambiental",
  ],
  "Canales de información": [
    "Canales de información",
  ],
  "Atención a cliente WHATSAPP": [
    "tiempo de espera",
    "Géneros de música y horarios en Hoteles Encore",
    "6:00am-6:00pm – Chill Out / Lounge",
    "6:00pm-12:00am (media noche) – Soft Rock",
    "Calificación final",
  ],
}
